#!/bin/bash
while [ 0 ]
do
echo "1 - show processes; 2 - kill process; 3 - exit"
read mode
if [ $mode -eq 1 ]
then
ps aux | grep "^$USER"
fi
if [ $mode -eq 2 ]
then
echo Enter PID:
read pid
kill $pid
fi
if [ $mode -eq 3 ]
then
exit 0
fi
done
